final List<Map<String, dynamic>> counties = [
  {"index": 1, "name": "Mombasa"},
  {"index": 2, "name": "Kwale"},
  {"index": 3, "name": "Kilifi"},
  {"index": 4, "name": "Tana River"},
  {"index": 5, "name": "Lamu"},
  {"index": 6, "name": "Taita-Taveta"},
  {"index": 7, "name": "Garissa"},
  {"index": 8, "name": "Wajir"},
  {"index": 9, "name": "Mandera"},
  {"index": 10, "name": "Marsabit"},
  {"index": 11, "name": "Isiolo"},
  {"index": 12, "name": "Meru"},
  {"index": 13, "name": "Tharaka-Nithi"},
  {"index": 14, "name": "Embu"},
  {"index": 15, "name": "Kitui"},
  {"index": 16, "name": "Machakos"},
  {"index": 17, "name": "Makueni"},
  {"index": 18, "name": "Nyandarua"},
  {"index": 19, "name": "Nyeri"},
  {"index": 20, "name": "Kirinyaga"},
  {"index": 21, "name": "Murang'a"},
  {"index": 22, "name": "Kiambu"},
  {"index": 23, "name": "Turkana"},
  {"index": 24, "name": "West Pokot"},
  {"index": 25, "name": "Samburu"},
  {"index": 26, "name": "Trans-Nzoia"},
  {"index": 27, "name": "Uasin Gishu"},
  {"index": 28, "name": "Elgeyo-Marakwet"},
  {"index": 29, "name": "Nandi"},
  {"index": 30, "name": "Baringo"},
  {"index": 31, "name": "Laikipia"},
  {"index": 32, "name": "Nakuru"},
  {"index": 33, "name": "Narok"},
  {"index": 34, "name": "Kajiado"},
  {"index": 35, "name": "Kericho"},
  {"index": 36, "name": "Bomet"},
  {"index": 37, "name": "Kakamega"},
  {"index": 38, "name": "Vihiga"},
  {"index": 39, "name": "Bungoma"},
  {"index": 40, "name": "Busia"},
  {"index": 41, "name": "Siaya"},
  {"index": 42, "name": "Kisumu"},
  {"index": 43, "name": "Homa Bay"},
  {"index": 44, "name": "Migori"},
  {"index": 45, "name": "Kisii"},
  {"index": 46, "name": "Nyamira"},
  {"index": 47, "name": "Nairobi"}
];
